### ISSUE TITLE
兄弟您好，我是找您帮忙的那个朋友

### ISSUE THREAD

**Issue by wdc63** [WeihanLi/ActivityReservation#1]
我现在发现几个的bug
1 禁用时间段存在比较严重的bug，第一，设置禁用时间段之后，发现后面的可选日期都被禁用，而前面的可选日期不被禁用，例如禁用日期设置为2017.12.15-2017.12.17，测试发现15号和16号均可以预约，而17号之后，包括18号19号都无法预约
2 禁用时间段无法删除
3 公告系统我在我这边怎么也无法保存，保存之后打开页面提示404错误，你的demo似乎是好的，不知道这是什么问题

**Comment by WeihanLi** [comment]
嗯，禁用时间段现在有点 bug，公告系统可能是权限问题，有时间帮你看一下

**Comment by WeihanLi** [comment]
BUG已修复
