### ISSUE TITLE
reservation-server pod CrashLoopBackOff

### ISSUE THREAD

**Issue by zhujinhu21** [WeihanLi/ActivityReservation#43]
reservation-server pod启动不了，使用openreservation/reservation-server:dev 镜像，用 kubectl logs 查看报错提示

Unhandled exception. System.TypeLoadException: Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitorFactory' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=3.1.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.

**Comment by WeihanLi** [comment]
升级 .NET5 的时候 MySQL 的驱动还没更新，还是 3.1 的，应该是 EFCore 内部有些破坏性的变更，等 5.0 发布了会更新上去

**Comment by WeihanLi** [comment]
MySQL 的支持不是特别好，估计还要一段时间才会正式发布，可以参考 issue <https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088>，我现在用的是 SQL Server，我加一下 Sqlite 支持

**Comment by zhujinhu21** [comment]
谢谢，我使用openreservation/reservation-server:20201111.2 这个镜像测试部署，用的dotnet 3.1版本。是不是不会报错

**Comment by zhujinhu21** [comment]
使用openreservation/reservation-server:20201111.2  可以运行

**Comment by WeihanLi** [comment]
好的

**Comment by WeihanLi** [comment]
先关掉这个 issue 了，可以通过 https://github.com/OpenReservation/ReservationServer/issues/45 追踪 MySQL 支持情况
