### ISSUE TITLE
单机版Docker部署失败

### ISSUE THREAD

**Issue by xinkecn** [WeihanLi/ActivityReservation#47]
docker拉下来
docker pull weihanli/activityreservation
运行
docker run -d -p 8900:80 --name=reservation weihanli/activityreservation

为什么镜像没生效，镜像自己就停了呢

**Comment by WeihanLi** [comment]
单机版需要指定 tag `standalone`

```
docker run -d -p 8900:80 --name=reservation weihanli/activityreservation:standalone
```

**Comment by WeihanLi** [comment]
docker 镜像更新了，升级到了 .NET Core 3.1

``` bash
# 删除旧容器
docker rm reservation -f
# 删除旧镜像
docker rmi weihanli.activityreservation:standalone
# 启动容器
docker run -d -p 8900:80 --name=reservation weihanli/activityreservation:standalone
```

**Comment by xinkecn** [comment]
感谢，已经可以pull下来，正常运行了。


但是发现以下几点
1. 预约完成后，拼图页面的特别慢，是否可以考虑增加关闭该功能的可选项？
2. 好像没有修改预约时间段的选项，不可以自由地预约选定的时间


希望越做越好，


xinke
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenReservation/ReservationServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenReservation/ReservationServer] 单机版Docker部署失败 (#47)





 
docker 镜像更新了，升级到了 .NET Core 3.1
 # 删除旧容器 docker rm reservation -f # 删除旧镜像 docker rmi weihanli.activityreservation:standalone # 启动容器 docker run -d -p 8900:80 --name=reservation weihanli/activityreservation:standalone

**Comment by WeihanLi** [comment]
1. 拼图页面是从腾讯云加载过来的，网速不好的话可能会有点慢，可以增加一个关闭该功能的配置，目前还没有，如果要修改的话，也很简单，可以参考后台预约的页面，后台预约的时候是不需要验证码的
2. 预约时间段是在后台预设好的，预约的时候不能自己改预设的时间段，在后台活动室管理的地方可以配置活动室的预约时间段（后台登录账号密码：admin/Admin888
