### ISSUE TITLE
大佬可以出个完整的教程么？

### ISSUE THREAD

**Issue by peaceanddemocracy** [WeihanLi/ActivityReservation#49]
大佬可以出个完整的教程么？
不用docker

**Comment by WeihanLi** [comment]
部署教程吗，主要是哪方面的教程？

**Comment by WeihanLi** [comment]
部署教程吗，主要是哪方面的教程？

**Comment by peaceanddemocracy** [comment]
部署教程，对docker不太熟悉，能不能出个非docker的教程，比如部署环境的安装这种的教程有么？

**Comment by WeihanLi** [comment]
可以有 👍

**Comment by peaceanddemocracy** [comment]
谢谢大佬，期待下，我系统是centos7+centos6，可以不用一键包，说明需要安装哪些环境以及关键步骤即可

**Comment by WeihanLi** [comment]
单机版的比较简单，更新了一下单机版的部署文档，可以参考： <https://github.com/OpenReservation/ReservationServer/blob/dev/docs/deploy/standalone.md>，相比之下，感觉还是 docker 比较简单方便一些
集群版的有点复杂，因为涉及到用户系统，现在是一个独立的用户系统，有点麻烦，还没更新
