### ISSUE TITLE
大佬有没有 ids4 的部署教程

### ISSUE THREAD

**Issue by FatuityCookie** [WeihanLi/ActivityReservation#52]

**Comment by WeihanLi** [comment]
我是基于这个项目部署的 <https://github.com/skoruba/IdentityServer4.Admin>，实际部署源码在这里 <https://github.com/OpenReservation/Identity>（后来一直没更新，建议可以使用原项目）

之前部署的时候有踩过几个坑，可以参考之前写的文章: <https://www.cnblogs.com/weihanli/p/12653954.html>
